name: Wander
version: "${version}"
main: au.lupine.wander.Wander
api-version: "1.20"
authors: [Fruitloopins]
description: A simple plugin to define custom wandering trader trades
website: https://lupine.au
folia-supported: true

permissions:
  wander.command.wander.reload:
    default: op
    description: Allows the user to reload the Wander config